project_id = "nxcvgziltgvkzfownswf"

[functions.parse-policy]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.provision-prospect]
verify_jwt = false
